version: '3.6'

services:
  book:
    expose:
      - 8090
    build:
      context: book
      dockerfile: book.dockerfile
    ports:
      - "8090:8090"
    environment:
      - EUREKA_ADDRESS=eureka-server:8070
    networks:
      - network1
    depends_on:
      - "config-server"
      - "eureka-server"
  statistics:
    expose:
      - 9010
    build:
      context: statistics
      dockerfile: statistics.dockerfile
    ports:
      - "9010:9010"
    environment:
      - EUREKA_ADDRESS=eureka-server:8070
    networks:
      - network1
    depends_on:
      - "eureka-server"
  config-server:
    expose:
        - 9000
    build:
      context: config-server
      dockerfile: server.dockerfile
    environment:
      - EUREKA_ADDRESS=eureka-server:8070
    ports:
      - "9000:9000"
    networks:
       - network1
    depends_on:
      - "eureka-server"
  eureka-server:
    expose:
      - 8070
    build:
      context: eureka-server
      dockerfile: eureka.dockerfile
    ports:
      - "8070:8070"
    networks:
      - network1
  zuul:
    expose:
      - 9100
    build:
      context: zuul
      dockerfile: zuul.dockerfile
    ports:
      - "9100:9100"
    environment:
      - EUREKA_ADDRESS=eureka-server:8070
    networks:
      - network1
    depends_on:
      - "eureka-server"
networks:
  network1:
    driver: bridge