spring:
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: 8500
      discovery:
        port: 8801
      config:
        watch:
          wait-time: 60
  application:
    name: consul-app
server:
  port: 8801