server:
   port: 9100
eureka:
   client:
      serviceUrl:
         defaultZone: http://${EUREKA_ADDRESS:localhost:8070}/eureka
zuul:
   prefix: /api
   routes:
      client:
         path: /client/**
         service-id: library-client
spring:
  application:
    name: zuul
