server:
  port: 9010
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ADDRESS:localhost:8070}/eureka
spring:
  application:
    name: statistics
  zipkin:
    base-url: http://{ZIPKIN_ADDRESS:localhost:9411}