server:
  port: 8090
#statistics:
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: localhost:9010,localhost:9020
#    ServerListRefreshInterval: 3000
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,info,health
spring:
  zipkin:
    base-url: http://{ZIPKIN_ADDRESS:localhost:9411}