#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/it-discovery/microservices
#          searchPaths: config

spring:
  profiles:
    active: native
server:
  port: 9000